### ISSUE TITLE
Compiling nulib2 on 64-bit Pi Linux

### ISSUE THREAD

**Issue by webspacecreations** [fadden/nulib2#14]
Pi 400 64-bit (Manjaro, but probably same case for the default 64-bit Raspberry Pi Linux)

./configure doesn't know what to do with 'aarch64' platform. The configuration script (especially the config.guess) is pretty dense. Any tips for getting this script to do its magic?

**Comment by fadden** [comment]
The `configure` script is generated by autoconf (https://www.gnu.org/software/autoconf/), from `configure.in`.  The config.sub / config.guess are copied from the autoconf package.

Looking at a recent source tree [here](http://git.savannah.gnu.org/gitweb/?p=autoconf.git;a=blob;f=build-aux/config.sub;h=63c1f1c8b5e2d881e106d8951a11c6c94ae6352b;hb=refs/heads/branch-2.70), `aarch64` does appear in those scripts.  So it may just be a matter of updating the configuration scripts.  Checking the [git log](https://github.com/fadden/nulib2/commits/master/nulib2/config.sub), it appears I've done that a few times in the past, but haven't in about 17 years.

I'll update this soon, but if you want to try it yourself you can download an autoconf distribution and just copy the `build-aux/config.sub` file into the nufxlib and nulib2 directories.

**Comment by fadden** [comment]
Newer scripts have been added.  Please pull the latest and give it a try.

**Comment by webspacecreations** [comment]
Thanks for the attention to this. Here are the results:
cd nulib2/nulib2
./configure seems to work fine. The only interesting line is:
config.status: WARNING:  'Makefile.in' seems to ignore the --datarootdir setting

make fails with the 
make: *** No rule to make target '../nufxlib/libnufx.a', needed by 'nulib2'.  Stop.

This message comes just after the following successful line:
gcc -g -O2 -Wall -Wwrite-strings -Wstrict-prototypes -Wpointer-arith -Wshadow -I. -I../nufxlib -I/usr/local/include -DHAVE_CONFIG_H   -c -o SysUtils.o SysUtils.c
