### ISSUE TITLE
Visual Studio 2015 build fix (MSC 1900)

### ISSUE THREAD

**Issue by char27** [fadden/nulib2#4]
I fixed my local version to build in VS2015.  I did not submit it since my C++ skills are somewhat limited and may a better way to address this. 
btw: I ran into this issue while after pulling down the latest CiderPress which contains this lib.

Building in VS2015 works fine with the following change (aside from upgrading the project).

Project: nufxlib, File: SysDefs.h, Lines 70 and 71 are replaced by;

/*
Char27 2015-11-01 - Fix for MSC >= 1900 (Visual Studio 2015)
// # define snprintf _snprintf
// # define vsnprintf _vsnprintf
*/
	#if _MSC_VER <= 1800 )
	#   define snprintf _snprintf
	#endif
	#if _MSC_VER <= 1800 )
	#   define vsnprintf _vsnprintf
	#endif

**Comment by fadden** [comment]
Looking around a bit I found this:

  http://stackoverflow.com/questions/2915672/snprintf-and-visual-studio-2010

The answer was recently updated for VS 2015.  Sounds like your solution is the correct approach, though I'd change the version check like this:

    diff --git a/nufxlib/SysDefs.h b/nufxlib/SysDefs.h
    index b6ff2b1..a46fea4 100644
    --- a/nufxlib/SysDefs.h
    +++ b/nufxlib/SysDefs.h
    @@ -67,8 +67,11 @@
     # include <direct.h>
     # define FOPEN_WANTS_B
     # define HAVE_CHSIZE
    +#if _MSC_VER < 1900
    +/* no snprintf until Visual Studio 2015 */
     # define snprintf _snprintf
     # define vsnprintf _vsnprintf
    +#endif
 
     #endif

**Comment by fadden** [comment]
I updated SysDefs in NufxLib and NuLib2, and propagated the change to CiderPress.  No changes to version numbers.  I don't have VS2015 to test with, but VS2013 and Linux are still happy.
