### ISSUE TITLE
Forked entries without resource fork data not handled correctly

### ISSUE THREAD

**Issue by fadden** [fadden/nulib2#5]
(reported by Ivan Drucker)

Given an extended file with a zero-length resource fork, GSHK will create an entry that doesn't have a data_thread for the resource fork, relying on the StorageType value to identify the file as extended.  NufxLib has some code for dealing with "missing" fork data, but doesn't appear to handle this situation (even with MaskDataless=true).

**Comment by IvanExpert** [comment]
Despite my weak C skills and my lack of familiarity with the code, I had a look, and I think I turned up a clue, anyway. At line 261 in thread.c, it says:
`if (!hasData && pArchive->valMaskDataless) {`

It looks, at least without understanding it more deeply, like it's not designed to accomdate situations where there's an extended file which has a data fork.

I changed this line to `if (true) {`, and sure enough, the simple2.shk archive showed as extended with `nulib2 -v`, and both forks could be extracted with `nulib2 -xe`, though it wanted to name them the same thing, so I had to use its rename option to manually change the resource fork to end in `r` like it's supposed to, and that had zero bytes, like it's supposed to.

(Attached is the simple2.shk archive for a demonstration of this issue. It contains a single extended file, simple.txt, which has a 15-byte data fork and a zero-length resource fork, and was created with GSHK. It will normally show the file as NOT extended with `nulib2 -v`, and generate an error when you try to extract it.)

I'm eager to get this bug fixed for a forthcoming release of A2SERVER which will require some automated extraction of BXY files made with GSHK, though I don't know if any of them actually contain any files like this (I could look, and if not, then there's no rush on my end). Do you think this is enough of a clue for you to have a look? If not, I might take a crack at a patch, though I'm guessing it would be without a full understanding of potential consequences and side effects.

[simple2.shk.zip](https://github.com/fadden/nulib2/files/72352/simple2.shk.zip)

**Comment by fadden** [comment]
Looking at the comments in the [ShrinkIt compatibility section](http://nulib.com/nufxlibapi.htm#shrinkit) of the NufxLib docs, I think my intent with "mask dataless" was to create a situation where the app using NufxLib was unaware the situation existed. I think NuExtract / NuExtractRecord are expected to behave correctly with or without that flag, but of course thread-based operations like NuExtractThread wouldn't work because there's no thread to operate on.

NuLib2 doesn't use NuExtractThread, except when extracting comments, which explains why it doesn't set "mask dataless".  CiderPress is a different story, of course.

The code you reference in Thread.c appears to be doing something like this:

    if (record has any data-class thread)
        set hasData to true
    ...
    if (hasData is false)
        create fake entries

This only handles the case where there are *no* threads for file data.  In your case, there's a thread for the data fork, so it skips the fakery.  This code needs to be improved to create the "Miranda threads" when needed.

Looks like the other part of the equation is at the bottom of Nu_ExtractRecordByPtr.  It made a similar mistake, using a variable `hasInterestingThread` to indicate that the record had a data-class thread, and therefore no special processing was required.  The code to create an empty resource fork already exists, so I think this needs to be modified to expect 1 or 2 data-class threads, and create an empty file for whatever is missing.

**Comment by fadden** [comment]
I created an archive with the full matrix of zero vs. non-zero forks.  I did this by creating the various pieces on Linux with the filetype preservation extensions, adding them to a ShrinkIt archive with nulib2, extracting the archive in KEGS with GSHK, and finally creating a new archive with those files using GSHK.

The attached [forktest.zip](https://github.com/fadden/nulib2/files/72495/forktest.zip) includes both archives, as well as the input files.  

If all is working correctly, "nulib2 xe gshk.shk" will produce the same set of files seen in the "src" directory.  At present, the output is missing d0rN#040000 (i.e. the empty data fork from an extended file with stuff in its resource fork) and dNr0#040000r (the empty resource fork from an extended file with stuff in its data fork).

**Comment by IvanExpert** [comment]
Indeed. Let me know if there is anything I can do to assist.

**Comment by fadden** [comment]
[Change uploaded](https://github.com/fadden/nulib2/commit/f37b387cc602acf144d4c901fd639e0a92d03560).  Please give it a try.

**Comment by IvanExpert** [comment]
Seems great for the files we're talking about, but I may have found an edge case where it's doing the wrong thing. Stand by while I see if the archive I'm looking at is valid.

**Comment by IvanExpert** [comment]
I take it back. Seems to work beautifuly. Bonus points for "Miranda threads." Thanks!

**Comment by fadden** [comment]
Excellent.  I rolled the changes into [CiderPress](https://github.com/fadden/ciderpress/releases/tag/v4.0.2-a1) as well.
