### ISSUE TITLE
3.1.0a1 -- not expanding disk images correctly without -e

### ISSUE THREAD

**Issue by IvanExpert** [fadden/nulib2#7]
I think as of 3.1.0a1, if you use `nulib2 -x SHRINKIT.SDK`, it now says "expanding SHRINKIT" and then "extracting SHRINKIT", and the latter file, which is zero-length, overwrites the former. Does not occur in 3.0.0.

If you use -e, then you get both the disk image file ending in "i", and a zero-length file with just the file name. I think this latter empty file was being skipped before, but now it's being extracted, and with the same name as the real thing, overwriting it.

Perhaps it's a result of more widespread Miranda threads or something.

**Comment by fadden** [comment]
Whoops. It might be trying to synthesize a zero-length data fork.

**Comment by fadden** [comment]
[This change](https://github.com/fadden/nulib2/commit/20fe7efb4d37fedf807416c16d74d51d893ea48a) should fix it.

I ran the tests I used for the previous change and didn't find any regressions.

**Comment by IvanExpert** [comment]
Just wanted to mention that I checked this out and it appears fixed.
