### ISSUE TITLE
Makefile.in: Explicit %.o: %.c rules for static and shared would make shared lib work

### ISSUE THREAD

**Issue by iKarith** [fadden/nulib2#8]
Right now, your Makefile.in for nufxlib doesn't work for building a library.  The reason is that while you include `-shared` when linking, the code to be linked has not been compiled with position independent code, and thus cannot be linked into a shared library.  You're depending on a GNU make feature to compile object files, an implicit rule that looks something like this:

``` make
%.o: %.c
	$(CC) $(CPPFLAGS) $(CFLAGS) -c $@
```

The problem there is that nowhere in CFLAGS do you set anything to produce position-independent code (nor should you directly since CFLAGS also gets used for static library code.)  With gcc (or clang in gcc emulation), -fPIC will always generate position-independent code, however within certain constraints you may be able to get smaller/faster code out of -fpic. I don't think anybody is producing hundred megabyte ShrinkIt archives, however, so it probably doesn't matter if the code's a little bigger to choose the compatible option.

Options for building both often include the use of object directories and name transformations so that you have one rule to build static objects without -fPIC and one to build shared objects with -fPIC, and you specify both rules to control which flags get used for which.

**Comment by fadden** [comment]
Hmm. I think once upon a time this worked, but it's certainly not working now.

I don't see a problem with just dropping -fPIC into CFLAGS. The library only grows by about 6KB, and I don't think a slight change in performance will be noticed by anyone.

**Comment by fadden** [comment]
Simple fix: https://github.com/fadden/nulib2/commit/9fdc77a1088f805429d9738cfc298f1ccf44127b

**Comment by iKarith** [comment]
Appreciate it, I'll test this out and let you know how it goes.

Joseph
